#!/usr/bin/bash
(
  # subshell, since exit status is != 0 if changes need to be made
  npm exec -- prettier -l . > .tmp-commit
)
npm run fmt
formatted_files=$(grep '^src/' .tmp-commit)
rm .tmp-commit
if [[ $(echo $formatted_files|wc -l) -gt 0 ]]; then
  git add $formatted_files
fi
npm run lint
npm run test
